### ISSUE TITLE
Handle empty/blank output

### ISSUE THREAD

**Issue by rk** [darsain/laravel-console#9]
Sometimes I hit a situation where the output from code in the console is blank. Whenever this happens I get:

```
Unhandled Exception

Message:

Undefined offset: -9223372036854775808
Location:

laravel/helpers.php on line 597
Stack Trace:

#0 laravel/laravel.php(42): Laravel\Error::native(8, 'Undefined offse...', '/Users/woodstre...', 597)
#1 laravel/helpers.php(597): Laravel\{closure}(8, 'Undefined offse...', '/Users/woodstre...', 597, Array)
#2 bundles/console/models/console.php(34): get_file_size(0)
#3 bundles/console/controllers/console.php(55): Console::execute('echo '';')
#4 [internal function]: Console_Console_Controller->post_execute()
#5 laravel/routing/controller.php(325): call_user_func_array(Array, Array)
#6 laravel/routing/controller.php(285): Laravel\Routing\Controller->response('execute', Array)
#7 laravel/routing/controller.php(165): Laravel\Routing\Controller->execute('execute', Array)
#8 laravel/routing/route.php(153): Laravel\Routing\Controller::call('console::consol...', Array)
#9 laravel/routing/route.php(124): Laravel\Routing\Route->response()
#10 laravel/laravel.php(167): Laravel\Routing\Route->call()
#11 public/index.php(34): require('/Users/woodstre...')
#12 {main}
```

Perhaps just show an empty output region, or an "(no output)" message?

**Comment by darsain** [comment]
It does handle clean output. You are probably using an old version with bug in some versions of PHP where Laravels get_file_size() helper cannot accept null value. That has been fixed 2 months ago.

Please confirm. To update bundle:

```
> php artisan bundle:upgrade console
> php artisan bundle:publish console
```

**Comment by rk** [comment]
You are correct, I hadn't realized that there was an update to the console bundle. Sorry about that.
